version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -uroot -p12345678 -e 'select 1;'"
      interval: 1s
      retries: 20
    environment:
      MYSQL_ROOT_PASSWORD: 12345678

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://db:3306/eshop
      DB_USER: root
      DB_PASSWORD: 12345678


