export { default as Header } from './Header';
export { default as PhoneCard } from './PhoneCard';
export { default as BreadcrumbsPhoneDetails } from './BreadcrumbsPhoneDetails';
export { default as PhoneImage } from './PhoneImage'
export { default as Spinner } from './Spinner'
export { default as PhoneColorPicker } from './PhoneColorPicker'
export { default as PhoneStoragePicker } from './PhoneStoragePicker'
export { default as InfoCard } from './InfoCard'
export { default as Qty } from './Q-ty'
